name: Experiment
on: 
  workflow_dispatch:
  push:
    paths:
      - 'identity-server-info.json'
    

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: List file
      run: |
        echo "Running"
        echo ${{ github.event.pull_request.title }}
        echo ${{ github.head_ref }}
        echo ${{ github.base_ref }}
        echo ${{ github.ref }}
        echo ${{ github.sender }}
        echo ${{ github.commits.author }}
        echo ${{ github.commits.url }}
