name: Experiment
on: 
  workflow_dispatch:
  push:
    paths:
      - 'identity-server-info.json'
    

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || 
      ( github.event_name == 'push' && 
      github.triggering_actor == 'AmshikaH' &&
      github.event.commits[0].author.name == 'test-bot-amshi' )
    steps:
    - name: List file
      run: |
        echo "${{ github.triggering_actor }}"
        echo "${{ github.event_name }}"
        echo "${{ github.event.sender.login }}"
        echo "${{ github.event.commits[0].author.name }}"
