name: Experiment
on: 
  workflow_dispatch:
  push:
    paths:
      - 'identity-server-info.json'
    

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: List file
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "${{ github.triggering_actor }}"
        echo "${{ github.event.pusher.login }}"
        echo "${{ github.event.sender.login }}"
        echo "${{ github.event.commits.author.name }}"
