name: Experiment
on: 
  pull_request:
    types:
      - closed

jobs:
  job1:
    name: Debug
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: List file
      run: echo "Running"
