name: Experiment
on: 
  workflow_dispatch:
  pull_request:
    types:
      - closed
    paths:
      - 'identity-server-info.json'
    

jobs:
  job1:
    name: Debug
    if: github.event_name == 'workflow_dispatch' || 
      ( github.event.pull_request.merged == true && 
      github.event.pull_request.merged_by.login == 'AmshikaH' &&
      startsWith(github.head_ref, 'product-info-changes') )
    runs-on: ubuntu-latest

    steps:
    - name: List file
      run: |
        echo "Running"
        echo ${{ github.event.pull_request.title }}
        echo ${{ github.head_ref }}
