name: Experiment
on: 
  schedule:
  - cron: '10 2,17 * * *'

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with: { ref: master }
    - name: List file
      run: ls
